### ISSUE TITLE
Interaction between different material

### ISSUE THREAD

**Issue by SimonZeng7108** [erizmr/taichi_sph#3]
Hi Mingrui

Thanks for the work.

When I change the material in the add_cube function in demo.py to 0, it almost works like a black hole and any particle passing through it will vanish. I compared this repo to your previous repo on sph solvers, I couldn't spot the reason, do you know why?

best,

Simon

**Comment by SimonZeng7108** [comment]
simply add two lines of code in compute_pressure_forces and compute_non_pressure_forces

`if self.ps.material[p_i] != self.ps.material_fluid: `
`self.d_velocity[p_i].fill(0)`

![timestep_001372](https://user-images.githubusercontent.com/52696979/158141179-9843b655-0956-49d8-b8db-8f0190c39b64.png)

**Comment by erizmr** [comment]
Hi @SimonZeng7108 , thanks for reporting this and help fixed the bug!
